Theofilus Arkhi Susanto
(theofilus.arkhi@mail.ugm.ac.id)
25/555265/PPA/07030

In [1]:
%pip install numpy opencv-python matplotlib

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

# Convolution function

In [22]:
kernel = [
    [0,1,0],
    [1,0,1],
    [0,1,0]
]

def multiplication(kernel, submatrix):
    kernel_size = len(kernel)
    sum = 0
    for i in range(kernel_size):
        for j in range(kernel_size):
            sum += kernel[i][j]*submatrix[i][j]
    return sum

def convolution(kernel, matrix):
    kernel_size = len(kernel)
    padded = np.zeros((len(matrix)+2, len(matrix[0])+2))
    ret = np.zeros_like(padded)
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            padded[i+1][j+1] = matrix[i][j]

    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            minplus = kernel_size//2
            start_y = i+1-minplus
            start_x = j+1-minplus
            ret[i+1][j+1] = multiplication(
                kernel, 
                [arr[start_x:start_x+kernel_size] for arr in padded[start_y:start_y+kernel_size]]
                )
    return np.round(ret)
            


In [23]:
matrix=[
    [3,6,2,5,5],
    [2,1,0,2,3],
    [4,1,3,2,1],
    [2,2,1,0,6],
    [3,4,2,0,0]
]

In [24]:
convolution(kernel, matrix)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  8.,  6., 11.,  9.,  8.,  0.],
       [ 0.,  8.,  9.,  8., 10.,  8.,  0.],
       [ 0.,  5., 10.,  4.,  6., 11.,  0.],
       [ 0.,  9.,  8.,  7.,  9.,  1.,  0.],
       [ 0.,  6.,  7.,  5.,  2.,  6.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

# Spatial Filtering

In [25]:
matrix=[
    [3,6,2,5,5],
    [2,1,0,2,3],
    [4,1,3,2,1],
    [2,2,1,0,6],
    [3,4,2,0,0]
]
kernel_sharpen = [
    [1,1,1],
    [1,-8,1],
    [1,1,1]
]
kernel_smoothing = [
    [0.11,0.11,0.11],
    [0.11,0.11,0.11],
    [0.11,0.11,0.111]
]

In [26]:
convolution(kernel_sharpen,matrix)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., -15., -40.,  -2., -28., -30.,   0.],
       [  0.,  -1.,  13.,  22.,   5.,  -9.,   0.],
       [  0., -24.,   7., -15.,   0.,   5.,   0.],
       [  0.,  -2.,   4.,   6.,  15., -45.,   0.],
       [  0., -16., -22.,  -9.,   9.,   6.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [28]:
convolution(kernel_smoothing,matrix)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 2., 2., 2., 0.],
       [0., 2., 2., 2., 3., 2., 0.],
       [0., 1., 2., 1., 2., 2., 0.],
       [0., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

"kernel_sharpen" is useful in case of blurred image, while "kernel_smoothing" is useful when there is noise in the image.

# Sharpening with blurring operation

sigma^2 = 0.5

		0.14	0.37	0.14
		0.37	1	0.37
		0.14	0.37	0.14


In [29]:
matrix=[
    [3,6,2,5,5],
    [2,1,0,2,3],
    [4,1,3,2,1],
    [2,2,1,0,6],
    [3,4,2,0,0]
]
kernel_sharpen_blurring = [
    [0.14,  0.37, 0.14],
    [0.37,  1,    0.37],
    [0.14,  0.37, 0.14],
]


In [30]:
convolution(kernel_sharpen_blurring,matrix)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 6., 8., 6., 9., 8., 0.],
       [0., 6., 6., 5., 7., 7., 0.],
       [0., 6., 5., 5., 6., 5., 0.],
       [0., 6., 7., 5., 4., 7., 0.],
       [0., 6., 7., 4., 2., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# Discussion

Filtering should be used rather than pixel-based method if the problem with the image is spatial in nature. The examples of spatial problems are blurred image, noise, or the image is too sharp.